# -*- coding: utf-8 -*-
"""PRODIGY_GA_01_GPT2_Text_Generation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ATp-B3Ptk003jcH_RLz0ZPwaA7NzWG3Y
"""

!pip install transformers torch

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

result = generator(
    "Artificial Intelligence is",
    max_length=50,
    num_return_sequences=1
)

print(result[0]["generated_text"])